services:
  be-bananahrm:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: hrm_api
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    restart: unless-stopped
    networks:
      - bananahrm-net

  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - bananahrm-net

  fe-bananahrm:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: hrm_fe
    ports: 
      - "3000:3000"
    env_file:
      - ./fe/.env
    restart: unless-stopped
    networks:
      - bananahrm-net

  # mysql-container:
  #   image: mysql:9
  #   ports:
  #     - 3307:3306
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #   container_name: mysql-container
  #   restart: unless-stopped
  #   env_file:
  #     - ./.env
  #   networks:
  #     - bananahrm-net
networks:
  bananahrm-net:
    driver: bridge
