services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: hrm_api
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    restart: always
    networks:
      - bananahrm-networks

  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - bananahrm-networks

networks:
  bananahrm-networks:
    driver: bridge
