name: Deploy Spring Boot to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            submodules: false
        - name: Setup JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '21'

      # Bước 2: Build Spring Boot (nếu dùng Maven)
        - name: Build Spring Boot Application
          run: |
            cd ./api
            mvn clean package -DskipTests

        - name: Login Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  
      # Bước 3: Thiết lập Docker Buildx
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
          id: buildx
  
      # Bước 4: Build và đẩy Docker image hỗ trợ ARM64
        - name: Build and push Docker image for ARM64
          uses: docker/build-push-action@v6
          id: docker_build
          with:
            context: ./api
            file: ./Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/bananahrm:latest
        # Step 5: Redeploy on Koyeb using API key
        - name: Redeploy on Koyeb
          run: |
            curl -X POST https://app.koyeb.com/v1/services/${{secrets.KOYEB_ID}}/redeploy -H "Authorization: Bearer ${{secrets.KOYEB_API_KEY}}" -H "Content-Type: application/json" -d "{ \"deployment_group\": \"prod\", \"use_cache\": true, \"skip_build\": false}"

